### ISSUE TITLE
Workflow guidelines on API link don't show

### ISSUE THREAD

**Issue by paulomcnally** [nodejs/nodejs.org-archive#102]
https://github.com/joyent/node/pull/14570

**Comment by paulomcnally** [comment]
Ping @misterdjules

**Comment by misterdjules** [comment]
Thank you for reporting this issue, please see my feedback in https://github.com/joyent/node/pull/14570#issuecomment-91646287.

**Comment by misterdjules** [comment]
Fixed in https://github.com/joyent/node/commit/de904033fa95f0993bd8583108ac0efcda8947af, thank you again @paulomcnally!
