### ISSUE TITLE
Adding link to Node Advisory Board website

### ISSUE THREAD

**Issue by shammond2000** [nodejs/nodejs.org-archive#105]
Chris Williams built a web site that provides updates from the Node AB.  The URL is http://nodeadvisoryboard.com.  I propose we add a link to this web site from the home page of nodejs.org so it is easy to find.

**Comment by fhemberger** [comment]
@shammond2000 @voodootikigod @mikeal Will this site still be relevant in the future with the Node Foundation in place? (Sorry, lost track a bit)
