### ISSUE TITLE
Web page to communicate information about Node.js Foundation

### ISSUE THREAD

**Issue by shammond2000** [nodejs/nodejs.org-archive#106]
I would like to create a web page that communicates more information about the Node.js Foundation and the status of the work to stand it up.  I would like this to be linked from the home page of nodejs.org.  Here is an introduction that I propose and some sections that can link to content that is being generated.  Comments welcome.
# 

Web page for Foundation

A group of organizations is coming together to create a neutral foundation for Node.js.  The goal is to accelerate the development and adoption of Node through a community-driven, neutral steward.  The foundation will have two organizations in it.  The first is the Technical Steering Committee that will provide technical leadership of the project.  The second is the Board of Directors that will provide services including funding, financial management, community development, marketing, and legal management.  We strive to further the success of Node by delivering distinct value to the users of Node, creating a level playing field that supports a vibrant ecosystem of product and service vendors, and attracting and developing an energized community of contributors.

Sections:

Blogs

Overall work plan with dates

Overview deck

FAQ

Intro to Foundation Members
-   Joyent
-   IBM
-   Microsoft
-   Fidelity
-   Apigee
-   SAP
-   PayPal

Foundation documents
-   by-laws
-   membership agreement
-   TSC charter
-   Governance docs

**Comment by misterdjules** [comment]
@shammond2000 What did you have in mind for blogs? Is that links to existing blogs, or blogs directly integrated in the website?

Is the "overview deck" a keynote/powerpoint slides deck?

**Comment by shammond2000** [comment]
@misterdjules the blogs that are being written can be posted elsewhere so this page can just contain the links.

The decks are in powerpoint and can also be converted to PDF.

**Comment by shammond2000** [comment]
@misterdjules I have a few backgrounders and bios from some of the Foundation members now and I will have a blog from the Linux Foundation ready in the next few days.  Any thoughts on when the page will be ready for this content?

**Comment by misterbisson** [comment]
I'm working to put together a draft page based on @shammond2000's outline above. Can anybody give me pointers to the work plan, by-laws, membership agreement, charter, and governance docs?

**Comment by shammond2000** [comment]
Adding Mike Dolan from the Linux Foundation. He should have these. 

Thx

Scott R. Hammond
President and CEO
Joyent

**Comment by misterdjules** [comment]
@misterbisson I was too busy last week to help on that front, but I have some time available this week. So if you need any help to put that content into the website, please let me know and we can work together.

**Comment by misterbisson** [comment]
My draft of the content is coming together in ~~https://gist.github.com/misterbisson/cfe2275e1c7a9e47cbd6~~ https://github.com/joyent/node-website/pull/113 / https://github.com/misterbisson/node-website/blob/foundation-106/doc/foundation/index.md

**Comment by misterdjules** [comment]
@misterbisson Thank you! @robertkowalski @geek I should be able to find some time to finish this before the end of this week, but if you also have some time to do that, please raise your hand as I already have a lot on my plate :)

**Comment by misterdjules** [comment]
Done in #115.

**Comment by misterdjules** [comment]
Late update:

Landed in 40d35ea3a3151b260633510e8e53af8ca3526f94 and subsequent fixups 65aed7e53eb52619be9f31b003dbfc4bfe377a77 and 9522ec5bd37d360f9d5e499a2244ef5ecdb0b977. 

Deployed at https://nodejs.org/foundation/.
Thank you!
