### ISSUE TITLE
404 on nightly link.

### ISSUE THREAD

**Issue by hemanth** [nodejs/nodejs.org-archive#11]
[this](http://jenkins.nodejs.org/html/nightlies.html) link returns:

```
{"code":"ResourceNotFound","message":"/html/nightlies.html"}
```

**Comment by bithavoc** [comment]
+1 `http://nodejs.org/download/` is pointing to `http://jenkins.nodejs.org/html/nightlies.html` which is a broken link.

**Comment by hemanth** [comment]
@bithavoc `http://nodejs.org/download/` is up

**Comment by bithavoc** [comment]
@hemanth the link called `Nightly Builds` inside the page `http://nodejs.org/download/` is broken because is pointing to `http://jenkins.nodejs.org/html/nightlies.html`.

**Comment by tjfontaine** [comment]
The nightlies are broken for the moment -- they will be fixed around the 0.12 release with a more crisp solution that involves a build for every commit of node for every one of our supported platforms

**Comment by bithavoc** [comment]
+1

**Comment by hemanth** [comment]
:+1:

**Comment by hemanth** [comment]
Thanks @tjfontaine :)

**Update 0:** Still noticing the same.
