### ISSUE TITLE
Windows download link

### ISSUE THREAD

**Issue by daguej** [nodejs/nodejs.org-archive#123]
The homepage (/) points to the x64 installer, but the link on /downloads (the one above the table of platforms/architectures) points to the x86 installer.

![screenshot](https://cloud.githubusercontent.com/assets/354349/8260148/8fdaefdc-1676-11e5-9d48-37e6b387b1e3.png)

The links should be consistent.

**Comment by fhemberger** [comment]
The download button on the homepage is adjusted with JS to match your current OS/architecture.

**Comment by daguej** [comment]
So the same thing should happen to the big button on the downloads page.

**Comment by fhemberger** [comment]
Fixed on current nodejs.org website.
