### ISSUE TITLE
Updates for Foundation Announce

### ISSUE THREAD

**Issue by jasnell** [nodejs/nodejs.org-archive#128]
Opening this issue for tracking. At Todd Benzies request, I am currently working to make a number of short-term updates to the website for the Foundation announce on 2015-06-16. These include:
1. Removing the "Sponsored by Joyent" branding on the various pages
2. Adding the usual Linux Foundation boilerplate header/footer
3. Adding the info@nodejs.org and trademark@nodejs.org contact points
4. Updating the Trademark Guidelines to reflect the Foundation's license to use the Node.js trademark
5. Adding an information request form for Foundation membership.
6. Updating the initial list of Foundation members.

These changes will need to go live on Tuesday, June 16th. However, as I'm going to be on vacation that day, I'll need someone else to actually review and land the changes. This is a time sensitive update and the actual list of Foundation members is confidential until the announce actually happens so the PR cannot be posted and landed until June 16th. I'll will open the PR Tuesday morning immediately before I head out the door. 

/cc @joyent/node-collaborators @mikeal @misterdjules @rvagg @Fishrock123

**Comment by rvagg** [comment]
I'm unsure where the website is currently hosted, I'm guessing on a Joyent machine somewhere? Who are the people that can make these changes? I think I recall that @misterdjules and @robertkowalski were on that list, I think we need a commitment from one or more of those people to work on this.

Perhaps @nodejs/website has made progress on convergence and can be given responsibility for this?

**Comment by jasnell** [comment]
I've already made the majority of the changes. I'll submit a PR on Tuesday
morning. I'm not sure who will be able to actually deploy to the server but
everything will be good to go by then. There's a short runway of time on
this one to coincide with the foundation announce on Tuesday.

**Comment by misterdjules** [comment]
I can take care of that, although I have a doctor appointment on June 16th at 10:45 in the morning, so it will either be deployed before 10:00am, or after/around 1:00pm.

@jasnell Have you been able to test these changes at least locally? Otherwise we might have some last minute unexpected issues that would prevent us from deploying these changes on June 16th.

**Comment by Fishrock123** [comment]
> Adding the usual Linux Foundation boilerplate header/footer

What exactly is that?

**Comment by jasnell** [comment]
@Fishrock123, look at http://cloudfoundry.org/index.html ... the Linux
Foundation boiler plate is the one line at the top and the copyright
statements at the bottom, slightly customized for the node.js site.

**Comment by Fishrock123** [comment]
Um, we don't need to keep that top header forever, right?

**Comment by rvagg** [comment]
The two lest intrusive versions of the LF boilerplate of their collab projects are these, perhaps we just copy them?
- https://www.tizen.org/
- https://letsencrypt.org/

**Comment by jasnell** [comment]
Perhaps longer term yes. For the time being we are under a time crunch. The
updates need to be in place by 7am eastern time on the 16th. The PR I will
be submitting soon is a bit of a quick stopgap. The design can, and I'm
sure will, be iterated on further.

Perhaps more importantly, the update includes the current foundation
members list and the updated trademark policy for the node.js mark.

**Comment by rvagg** [comment]
Note that the press release for the foundation is going live at 7:00 a.m. ET tomorrow.

@jasnell are you still around today? Could you get the changes to me perhaps? I have the release and list of members so there's not a confidentiality problem, I'm just concerned about timing here because the release will go live and the site will be very delayed. 7am ET is only 9pm for me so I'll be up and about and can easily work on this.

I just don't have access to the site, is there someone on this repo that will be around early tomorrow that I can collaborate with? Or perhaps I can be given access to push the changes?

**Comment by jasnell** [comment]
I'll email you the patch. I'll be opening the PR at midnight pacific time to ensure that the member list does not go public until June 16th. @misterdjules is set to push the updates to the site but needs to figure out the proper timing. He can provide you with the information necessary to get the changes pushed.

**Comment by misterdjules** [comment]
@rvagg I was about to take care of this, but that would mean waking up at 4am, which I'm not very excited about. If you want to deploy these changes, send me your public key and you'll be able to do that.

**Comment by rvagg** [comment]
4am .. that'd be dedication on your part!

```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0tlwoL1w8d8IIEKyb9bKQDUiScgveuGIo+RSrGoj+OxzpzR1Bfiz7NLHaU5UKoXrcL9gnoxaOgnUGzeA6D3eL3gUatUlFT5r3D1jrz9biRTXhkCd5CC+r9J+4zjXQ4XFa8wmalxheCpsxhbeLOikIn3GegjfLN/3pIfYlURfHt5If8VRaHKNwJcaLNTcx49l4VYGq8GccsLpcEHDTaLdx9ultkWINx0mfHjCyQ+Fqbb2OXkvycC2hj61IaWIijUdLSgvOw39eZin97yQcw+9Dw+JjasggI9bYWOj1zfB3BVHfxQDFmGCmJ8lr2922DWKA5u+T2JEQ8YGw0htKnwGuw==
```

just let me know what to do, feel free to email me if you prefer.

**Comment by jasnell** [comment]
Just sent the patch @rvagg ... if you can let me know if that applies cleanly for you and works, then I'll skip opening the PR and let you run with it from there. It would be best to hold off on the PR until right before 7am anyway.
