### ISSUE TITLE
Minor grammar fix needed in website footer

### ISSUE THREAD

**Issue by pixelchutes** [nodejs/nodejs.org-archive#131]
Just spotted a [minor grammatical error](https://github.com/joyent/node-website/commit/8c04496d338d1026426a46be47c19813a5922d4b#diff-3cccff1d628dba7d629fef7eeee50d94R120) in the updated footer: `its` vs. `it's`

**Comment by fhemberger** [comment]
@rvagg @misterdjules Can you please deploy this little change?

**Comment by misterdjules** [comment]
@fhemberger Done thank you @pixelchutes and @fhemberger :+1:

**Comment by pixelchutes** [comment]
You're welcome! Sorry I missed the other templates in my PR.
