### ISSUE TITLE
Use high-res image for Linux Foundation header

### ISSUE THREAD

**Issue by pfmooney** [nodejs/nodejs.org-archive#133]
Unlike the rest of the images on the site, the Linux Foundation header is neither SVG nor high resolution.  On high DPI screens, it looks poor compared to the rest of the content.

**Comment by fhemberger** [comment]
Yes, I'm not happy with the header either as it doesn't really look good on mobile as well.

**EDIT:** Found one version in higher resolution: http://collabprojects.linuxfoundation.org/sites/all/themes/lfcollab/images/lfcollab_logo.png

**Comment by pfmooney** [comment]
Perhaps they can be reached for a vector version.

**Comment by indexzero** [comment]
@pfmooney @fhemberger if we can get the fonts used then we can make our own vector of it.

**Comment by snostorm** [comment]
As another backup source, http://collabprojects.linuxfoundation.org/sites/collabprojects/files/lf_collaborative_projects_brochure.pdf has a vector version embedded

**Comment by pfmooney** [comment]
Looks great.  Thanks @fhemberger.
