### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by fitzage** [nodejs/nodejs.org-archive#134]
When Joyent stuff was removed from the footer, there was an artifact left of a vertical line that no longer makes sense. Also, the columns should perhaps be rebalanced to avoid having Downloads hanging off by itself looking lonely.

**Comment by indexzero** [comment]
@fitzage just to confirm, is this the visual artifact you're mentioning?

![screen shot 2015-06-16 at 3 13 37 pm](https://cloud.githubusercontent.com/assets/4624/8195863/b01f1f04-143a-11e5-82b4-34895298d966.png)

**Comment by fitzage** [comment]
Yes.
