### ISSUE TITLE
io.js Website WG + node-website Meeting

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org-archive#137]
Hey there. I'm a contributor to the io.js Website WG, and I've got a few questions.

We've been stuck in a sort of limbo in terms of where we're at with the merger. We don't really know how to proceed, but I think talking to you guys is the first step. How do you see the two projects merging? What can we at the Website WG do to help this process?

We've got a meeting tomorrow at 17:00GMT (1:00EST), and would love to have some or all of the contributors here to attend. Sorry for the short notice - if I would have known about this repo sooner, I'd have posted.

Here's our meeting issue: https://github.com/nodejs/website/issues/382

If you can attend, just comment with your Hangouts account (Google account, as I'm sure you know) and we'll either send you an invite or send you a link to join.

Thanks a ton!
- io.js Website WG

**Comment by misterdjules** [comment]
@bnb Thanks! I will attend, my google account is jgilli at nodejs dot org.

**Comment by misterdjules** [comment]
@joyent/node-website if you're interested in participating in these meetings, and haven't got the info about how to attend, please make sure you read that issue.

**Comment by misterdjules** [comment]
Closing for now, as I don't think we need to keep it open, thank you once again @bnb :+1:
