### ISSUE TITLE
Moving joyent/node-website to nodejs/nodejs.org

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org-archive#140]
Hello!

The Node Foundation Website Working Group would like to transfer this repo to nodejs/nodejs.org. @misterdjules said this was okay, but I wanted to get an express blessing in writing on it from someone in the repo. Once you guys give the thumbs up we can transfer it.

Thanks!

**Comment by misterdjules** [comment]
@bnb I just need to check a few more things before I can confirm this will have no impact on joyent/node. For instance, I want to be extra careful that it's not going to break our release process, as that process uses joyent/node-website. I should be able to confirm that shortly.

**Comment by bnb** [comment]
@misterdjules Okay, sounds great. Just let me know when you're ready.

**Comment by misterdjules** [comment]
@bnb By moving joyent/node-website to nodejs/nodejs.org, would HTTP requests to https://github.com/joyent/node-website/ be redirected to https://github.com/nodejs/nodejs.org?

If so then we can move this repository now.

**Comment by bnb** [comment]
@misterdjules No. There would exist no repository at https://github.com/joyent/node-website/ anymore - if you want, though, a new repository can be created with the same name, and have a link to the new repo in it's description and/or README. Let me know if that's okay.

**Comment by misterdjules** [comment]
@bnb https://help.github.com/articles/transferring-a-repository/#redirects-and-git-remotes seems to say that GitHub would redirect requests to the old repository/repository web page to the new one.

**Comment by snostorm** [comment]
Redirects do happen. See what happens when you go to [https://github.com/iojs/website](https://github.com/iojs/website) which was the io.js repo's name two names ago.

**Comment by misterdjules** [comment]
I'll do that when I have admin rights in the nodejs organization on GitHub, which might happen soon. In the meantime, if anyone else can do it, please feel free to do so.

/cc @mkdolan

**Comment by jasnell** [comment]
By moving joyent/node-website to nodejs/nodejs.org, github would automatically set up redirects from the original (joyent/node-website) to the new location. There would be zero interruption as far as git is concerned. @misterdjules, I've got the admin permits in the nodejs org to accept the transfer. If you'd like, I can go ahead and get that moved over now.

**Comment by jasnell** [comment]
I will note that it's a two-step process. First, the repo has to be transferred, then it would be renamed.

**Comment by misterdjules** [comment]
@jasnell Please do it, and thank you!

**Comment by jasnell** [comment]
Done!
