### ISSUE TITLE
Node Foundation Evangelism WG request/heads up: Weekly Update

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org-archive#141]
I just wanted to quickly let you guys know that the Node Foundation Evangelism WG wants to immediately move what was formerly known as the io.js Weekly Update to the Node.js Weekly Update, hosted on the Nodejs.org blog. We'd like to do it this week to piggyback off the interest in the project from the Linux Foundation announcement. 

One of our contributors will be sending a PR later today, and I want to make sure there's nothing standing in the way of it being pulled and deployed to the Nodejs.org blog immediately. If there's any process that needs to happen, let me know and we'll start on that ASAP.

**Comment by misterdjules** [comment]
I don't see what could stand in the way of doing that, except that it'll need to go through the normal review process of any PR.

**Comment by mikeal** [comment]
The updates are already in markdown https://github.com/nodejs/evangelism/pull/104, just need to send a PR to the other repo.

**Comment by fhemberger** [comment]
@bnb Is this issue still relevant or will we handle this on new.nodejs.org?

**Comment by mikeal** [comment]
The evangelism group is now merging weekly updates in to the website repo and I ported all the old ones.
