### ISSUE TITLE
secure installer downloads

### ISSUE THREAD

**Issue by sirbarrence** [nodejs/nodejs.org-archive#15]
It would be great if nodejs.org were accessible over HTTPS - if not for the whole site, at least for the installer downloads. The only relatively secure alternative I can find is to checkout the source from github and build it myself.

**Comment by jclulow** [comment]
Merely making the website accessible over HTTPS does not guarantee the integrity of your downloaded file.  You need to download the `SHASUMS.txt.asc` manifest file, which is cryptographically signed.  When you verify that signature, and that the hash of your downloaded file matches that of the manifest, you can be reasonably confident that you received the software we built.

For example, if you have @tjfontaine in your http://keybase.io trust chain, you can trivially verify the signatures and compare with the downloaded file.  To illustrate this using a SmartOS system:

```
$ curl -O http://nodejs.org/dist/v0.10.26/SHASUMS.txt.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1554  100  1554    0     0   8422      0 --:--:-- --:--:-- --:--:-- 16357

$ keybase verify -S tjfontaine SHASUMS.txt.asc
info: Valid signature from keybase user tjfontaine (tracking remotely & locally)
info: Signed about a month ago (2014-02-19 at 00:40:07)

$ curl -O http://nodejs.org/dist/v0.10.26/node-v0.10.26-sunos-x86.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6105k  100 6105k    0     0  3073k      0  0:00:01  0:00:01 --:--:-- 3215k

$ digest -a sha1 node-v0.10.26-sunos-x86.tar.gz
e5bf3dae6a0597bb8be029f6f0119bea2f1612f0

$ grep node-v0.10.26-sunos-x86.tar.gz SHASUMS.txt.asc
e5bf3dae6a0597bb8be029f6f0119bea2f1612f0  node-v0.10.26-sunos-x86.tar.gz
```

**Comment by sirbarrence** [comment]
Thanks for the tip. There should be at least a link to the asc file on http://nodejs.org/download/ somewhere, preferably accompanied by the instructions you gave above. There's a link to SHASUMS.txt, but those are just hashes that mean nothing with regards to identity verification, right?

**Comment by jclulow** [comment]
`SHASUMS.txt.asc` is a signed version of the same content that's in `SHASUMS.txt`.
