### ISSUE TITLE
Shasums page incorrectly claims a hash of SHA256 

### ISSUE THREAD

**Issue by DeeplyUncertain** [nodejs/nodejs.org-archive#160]
The main [Shasums](https://nodejs.org/dist/v0.12.7/SHASUMS.txt.asc) document accessible from the downloads page incorrectly lists a hash type of SHA512.  All of the shasums listed appear to be SHA-1, which are actually [vulnerable](https://en.wikipedia.org/wiki/Sha1sum) to collision attacks.

It would be best to replace the sha1sums listed by the much longer, and more secure SHA512, but it is clearly worst to incorrectly list the hash type, thereby making the hash appear invalid to some users (as is currently the case).

**Comment by fhemberger** [comment]
@nodejs/build Do you know what hashing algorithm is used during build? Can you confirm this?

**Comment by bnoordhuis** [comment]
You can choose from either [SHA-1](https://nodejs.org/dist/v0.12.7/SHASUMS.txt.asc) or [SHA-256](https://nodejs.org/dist/v0.12.7/SHASUMS256.txt.asc).  SHA-1 is there for backwards compatibility, some tools depend on it.

The hash line in:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
```

Relates to the algorithm used for signing the .txt.asc file, not the algorithm for signing the binaries.

**Comment by rvagg** [comment]
^ yeah, that, see also https://nodejs.org/dist/v0.12.7/SHASUMS256.txt.asc & https://iojs.org/dist/latest/SHASUMS256.txt.asc which has SHA512 but are actually 256.

**Comment by fhemberger** [comment]
So would it make sense to sign SHASUMS256.txt.asc with SHA256 instead, so we don't confuse people? What cryptographic impact would this have?

**Comment by rvagg** [comment]
Probably not a whole lot at the moment, but if you're looking at SHASUMS256.txt then you wouldn't be confused, it's just the .asc signed one that has that hash in it. Changing it to sign with 256 would be a micro-optimisation to solve a _very_ minor user experience edge case IMO.

**Comment by fhemberger** [comment]
Ok, so should we close this issue as "won't fix" or keep it as "low priority, maybe some day"?

**Comment by bnoordhuis** [comment]
I say close, not a bug.

**Comment by DeeplyUncertain** [comment]
I know you already marked this as invalid, but the initial SHASUMS page says nothing about what SHA algorithm is actually used.  It would be nice to at least mark this somewhere for clarity's sake.  Thanks for the SHA-256 link and clarification.

**Comment by rvagg** [comment]
We have this on the io.js README: https://github.com/nodejs/io.js#verifying-binaries and I imagine we'll carry that over to the converged repo. If we continue to ship with SHA-1 for nodejs.org then we could clarify it there. My preference would be to ditch the SHA-1 file and move forward with just 256 but that's for another discussion, and either way we can clarify the wording.
