### ISSUE TITLE
Missing Error Documentation 

### ISSUE THREAD

**Issue by samholmes** [nodejs/nodejs.org-archive#162]
In my experience, Node.js will report many errors like EACCESS, EPIPE, etc. No where are these errors documented (what they mean and when they occur). This seems like a _big_ issue.

Why it's a pretty significant issue is because errors is one of the most common thing developers must handle, and a vague error is the worst kind of error. I believe Node.js can do better; I think _every_ error from Node.js core framework should be documented and explained.

**Comment by mikeal** [comment]
I totally agree, but this might be something that the docs WG can do a better job of resolving that the website WG. Would you mind logging this against their repo? https://github.com/nodejs/docs

**Comment by Fishrock123** [comment]
See https://github.com/nodejs/docs/issues/26#issuecomment-125826833 -- this exists in io.js's docs at https://iojs.org/api/errors.html, and will be in the converged docs too.
