### ISSUE TITLE
Getting space error while installing node-v0.12.7-x64.msi

### ISSUE THREAD

**Issue by neerajdwiv** [nodejs/nodejs.org-archive#163]
![untitled](https://cloud.githubusercontent.com/assets/13641031/9059070/76d625c0-3ac4-11e5-95c3-b7563778cc9e.png)

Throwing less space error, when it required only few MB but 70GB is free in that drive.

**Comment by fhemberger** [comment]
This is the repo for the Node.js **website**. If you're problem still persist, please open an issue here: https://github.com/joyent/node/issues.
