### ISSUE TITLE
Deploy?

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org-archive#164]
The old trademark policy is still showing on the website. Has this not been deployed in 2 weeks? Is there some kind of caching issue?

**Comment by snostorm** [comment]
I'm not in the loop on deploying the old website. @nodejs/website ?

**Comment by fhemberger** [comment]
Files are deployed correctly, but I just noticed, there are two different files:

trademark-policy.pdf (14 days old)
foundation-trademark-policy.pdf (2 months old)

And the latter one is linked in the footer.

**Comment by fhemberger** [comment]
So … I changed the links to only use `trademark-policy.pdf` everywhere and deleted the other file to avoid confusion. _One policy to rule them all …_

**Comment by fhemberger** [comment]
@snostorm For the old website, it's misterdjules, robertkowalski and me who can deploy.
