### ISSUE TITLE
Timeouts trying to fetch nodejs tarballs

### ISSUE THREAD

**Issue by saper** [nodejs/nodejs.org-archive#167]
We (node-sass) have been experiencing [build](https://t.co/wZQ4KsiY9r) [failures](https://t.co/8xUQ6Goinm) in pangyp/node-gyp process which downloads node source tarballs: 

We have [raised an issue with AppVeyor](https://help.appveyor.com/discussions/problems/2849-intermittently-unable-to-connect-to-nodejsorg) and they say they can consistently reproduce that.

Are there any networking/hosting/performance issues with the site?

**Comment by Fishrock123** [comment]
Hmmm the one is an `ETIMEDOUT`...

cc @nodejs/build

**Comment by Fishrock123** [comment]
cc also @misterdjules maybe

**Comment by Fishrock123** [comment]
Refs: https://help.appveyor.com/discussions/problems/2849-intermittently-unable-to-connect-to-nodejsorg, https://twitter.com/saperski/status/633821709972447232

**Comment by Fishrock123** [comment]
Hmm, looks like I can't connect to http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz without a retry. :/

**Comment by saper** [comment]
> Hmm, looks like I can't connect to http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz without a retry. :/

Here too. We can definitely rule out @AppVeyor.

**Comment by rmg** [comment]
blog.nodejs.org is on the same IP and also being really sluggish to respond. It's in Joyent's us-east-1 datacenter, but they don't have any sort of status page to check that I've been able to find.

**Comment by misterdjules** [comment]
@Fishrock123 @saper @rmg Thanks for reporting this issue, I'm getting in touch with operations at Joyent and I'll keep you updated.

**Comment by misterdjules** [comment]
@Fishrock123 @saper @rmg Do you still have issues with downloading node tarballs from nodejs.org? I couldn't reproduce the problem and so far we haven't been able to find anything that could cause errors on the machine that hosts these files.

**Comment by saper** [comment]
It is okay now. When we opened the issue it was pretty bad - almost no download could be completed without a retry. Just checking various @appveyor related issues it seems that this issue was [observed around August 12th](https://github.com/nodejs/nan/pull/411#issuecomment-130426396) or even [August 5th](http://help.appveyor.com/discussions/problems/2709-exception-calling-downloadstring-with-1-arguments-unable-to-connect-to-the-remote-server).

**Comment by thomassuckow** [comment]
nodejs.org has been really unreliable the last few weeks. It is currently down [165.225.133.150] as I see it from 3 locations. Not sure if any infrastructure is shared with NPM, but if there is it may also explain sporadic issues with NPM.

**Comment by Fishrock123** [comment]
> Not sure if any infrastructure is shared with NPM, but if there is it may also explain sporadic issues with NPM.

It's separate afaik.

**Comment by claudiorodriguez** [comment]
http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz times out but https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz doesn't for me

Also, I noticed the asset is served by a bare nginx - no CDN cache headers that I can see.
Wouldn't it make more sense to have these kind of assets served by CDN? (Cloudfront, Cachefly, Fastly, etc etc)
That would also help with origin server issues.

**Comment by dbolkensteyn** [comment]
FYI this issue seem to have gotten a lot worse - All the builds I relaunched this afternoon from @AppVeyor failed:

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) on project sonar-web:
Could not download Node.js from: http://nodejs.org/dist/v0.12.2/node.exe:
Could not download http://nodejs.org/dist/v0.12.2/node.exe:
Connect to nodejs.org:80 [nodejs.org/165.225.133.150] failed:
Connection timed out: connect -> [Help 1]
```

:+1: for CDN

**Comment by fhemberger** [comment]
Seems to be fixed. If this problem should resurface, please open a new issue at https://github.com/nodejs/new.nodejs.org/issues.

**Comment by saper** [comment]
One can notice things are different now. I have to solve captcha on the CDN from time to time... :(

Thanks everyone for working on this!
