### ISSUE TITLE
Nodejs download is timing out

### ISSUE THREAD

**Issue by abhisheksoni** [nodejs/nodejs.org-archive#170]
When i try to install nodejs it is timing out:

http://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz

**Comment by rvagg** [comment]
have you retried it? is it still timing out? if so, could you tell us what browser or client you are using, where you are located and what possible network configuration issues could be related (i.e. are you in a corporate environment with possible restrictions on the types of files you can download?)

I've not heard any problems with downloads from anyone else.

**Comment by danielkhan** [comment]
Works for me OSX / Austria (Cable) / Chrome / Safari / Firefox

**Comment by fhemberger** [comment]
Duplicate of #170.

**Comment by ximex** [comment]
@fhemberger this is #170

**Comment by fhemberger** [comment]
Sorry, meant #167 …
