### ISSUE TITLE
Broken links to API docs

### ISSUE THREAD

**Issue by disharmonized** [nodejs/nodejs.org-archive#173]
All old links to api docs like http://nodejs.org/docs/latest/api/globals.html#globals_dirname
now refer to https://nodejs.org/en/blog/#globals_dirname but should refer to https://nodejs.org/api/globals.html#globals_dirname

**Comment by fhemberger** [comment]
Duplicate of https://github.com/nodejs/new.nodejs.org/issues/124

**Comment by rvagg** [comment]
fixed, sorry
