### ISSUE TITLE
Where is 0.12.7 API docs???

### ISSUE THREAD

**Issue by disharmonized** [nodejs/nodejs.org-archive#174]
I know that 4.0.0 is great, but where is my legacy 0.12.7 API docs??

**Comment by fhemberger** [comment]
The same place they have been before: https://nodejs.org/docs/ ;)
We'll make this more clear on the website.

**Comment by fhemberger** [comment]
See https://github.com/nodejs/new.nodejs.org/commit/9ae9cef978f12856ae1aef69e24c690272e6d549
