### ISSUE TITLE
I want to make a mirror web site from http://nodejs.org/dist/

### ISSUE THREAD

**Issue by fengmk2** [nodejs/nodejs.org-archive#23]
How can I rsync from http://nodejs.org/dist/ ?

**Comment by fengmk2** [comment]
done http://cnpmjs.org/dist/

**Comment by kiranos** [comment]
Hi can you please share how you did this?

**Comment by fengmk2** [comment]
@kiranos I wrote a nodejs sync client to do this. And it's become part of https://github.com/cnpm/cnpmjs.org/pull/337

**Comment by wssgcg1213** [comment]
I found another way to do this simpliy.

https://www.serverpals.com/blog/setting-up-a-nodejs-dist-mirror
