### ISSUE TITLE
View license link fail on /industry/

### ISSUE THREAD

**Issue by mininao** [nodejs/nodejs.org-archive#28]
On the footer of the http://www.nodejs.org/industry/ page, the "View license" links sends to https://raw.githubusercontent.com/joyent/node/__VERSION__/LICENSE , without an actual version number

**Comment by lucasfcosta** [comment]
Just tested here, it seems this problem has already been fixed.

**Comment by mininao** [comment]
Doesn't look fixed to me :o !

**Comment by ThisIsMissEm** [comment]
I'm not sure if that page is even meant to exist still. Doesn't appear to be in the repository, so, I'm guessing it's just a relic left behind. /cc @tjfontaine

**Comment by dwlf** [comment]
Seems like footer as home and other pages should be on /industry/.

**Comment by fhemberger** [comment]
@robertkowalski @misterdjules I can't find this page in the repository. Is this still from an old version of the website? Can we remove the page? (also see #5)

**Comment by dwlf** [comment]
> I can't find this page in the repository.

Looks like that is https://github.com/joyent/node-in-the-industry which hasn't been updated in over a year.

**Comment by fhemberger** [comment]
Uh, @geek @tjfontaine and @isaacs already discussed to remove that page entirely:
https://github.com/joyent/node-in-the-industry/issues/68

So can we just remove it, please?

**Comment by bnb** [comment]
+1 for removing it.

**Comment by fhemberger** [comment]
I just moved the directory `/industry/` from the server, as it hasn't been updated for a year. Closing this issue now.
