### ISSUE TITLE
Markdown parsing of URLs

### ISSUE THREAD

**Issue by sscotth** [nodejs/nodejs.org-archive#29]
The contributing page has a link to the Wikipedia article on Git, but the ending ")" is cut off.

https://github.com/joyent/node-website/blob/52f8be7b55e3b4676cd6f8bee544412176ce61a8/doc/documentation/contributing/index.md

Looks to be the markdown compiler since the raw is correct.

https://github.com/chjj/marked/issues/366

**Comment by lucasfcosta** [comment]
It seems like there's no fix for this on the Marked repository, maybe we should just encode the link using `%29` instead of that ")".
