### ISSUE TITLE
top nav overflow on Firefox/Mac

### ISSUE THREAD

**Issue by trentm** [nodejs/nodejs.org-archive#30]
top nav overflow on Firefox: http://cl.ly/image/0U2B1l3S2x0V

This is Firefox Aurora, 32.0a2 (2014-07-21) on Mac

**Comment by ThisIsMissEm** [comment]
Screen size?

**Comment by trentm** [comment]
If I widen out to more than 2380 pixels wide it still overflows like that:
![screen shot 2014-09-12 at 3 55 09 pm](https://cloud.githubusercontent.com/assets/46866/4258304/fa50ecf0-3acf-11e4-8dc5-321c782d9dc9.png)

This is now with Aurora 33.0a2 (2014-09-02) on Mac.

**Comment by fitzage** [comment]
Hmmm…do you block typekit? I may have to widen it for the fallback fonts.

**Comment by trentm** [comment]
Well sleuthed. Yes, this is because Ghostery  (with my settings) was blocking typekit.
