### ISSUE TITLE
Please restore site!

### ISSUE THREAD

**Issue by matthewlopez0977** [nodejs/nodejs.org-archive#31]
I don't know if you updated the nodejs site, but it doesn't show all the information on mobile no more.

**Comment by ThisIsMissEm** [comment]
This'll need more information, what aren't you seeing that you expect to see?

**Comment by matthewlopez0977** [comment]
You have two documentation. One does not fully show on mobile. It's the black and white theme one, not the green and white theme one, but the black and white theme one... Refer to pic to understand why I repeat that a second time.

E-S4L
N-S4L
J-S4L

**Comment by dwlf** [comment]
@L2L2L there are no image attachments on this issue ( node-website #31 ).

**Comment by matthewlopez0977** [comment]
... Never mind.... The node website have two documentation on the same information; one is --somewhat-- mobile friendly and the other one isn't. It's not an real issues. But think you for replying. You can close this issues.

E-S4L
N-S4L
J-S4L
