### ISSUE TITLE
Some page will return 404 

### ISSUE THREAD

**Issue by Pana** [nodejs/nodejs.org-archive#4]
I visite the new site sometimes some page will return 404, such as the api, resource. about page

**Comment by bernhardw** [comment]
They only seem to be doing that after one has visited the blog on its subdomain. Most links are relative but don't exist on the blog subdomain, for example http://blog.nodejs.org/api.

**Comment by fitzage** [comment]
Yes, I made an error with the navigation on the blog. Fixed, waiting for deployment.

**Comment by tjfontaine** [comment]
Landed and pushed live
