### ISSUE TITLE
Position problem viewing API Documentation "View as JSON"

### ISSUE THREAD

**Issue by M-Medhat** [nodejs/nodejs.org-archive#44]
When clicking View as JSON in any of the [API documentation pages](http://nodejs.org/documentation/api/), the JSON data is not positioned correctly and it's hard to view as per the screenshot below.

I'm using Google Chrome v37.0.2062.122 on Mac OS X v10.9.2

![node-json](https://cloud.githubusercontent.com/assets/875226/4403735/8037be26-44a7-11e4-9626-08fa979aa022.png)

**Comment by kwhinnery** [comment]
Are you still experiencing this issue? I'm unable to reproduce.

**Comment by M-Medhat** [comment]
No, It's working now. I'll close the issue.
