### ISSUE TITLE
ugly Github ribbon 

### ISSUE THREAD

**Issue by Pana** [nodejs/nodejs.org-archive#5]
I think the new Github ribbon is very ugly.

**Comment by TooTallNate** [comment]
+1

**Comment by Volox** [comment]
+1
Also the download section colors are messed up for me.

Here (using Chrome 33 on Win 8.1 x64).
![screen](https://f.cloud.github.com/assets/1468697/2321628/d4ea9a08-a3a6-11e3-9ecb-32732722747c.png)

**Comment by gtramontina** [comment]
Same here... Kind of ugly gray hover effect.

**Comment by junosuarez** [comment]
what is this i don't even :dog2:

**Comment by mtharrison** [comment]
+1 ![screen shot 2014-08-10 at 22 31 23](https://cloud.githubusercontent.com/assets/916064/3870591/b69cf134-20d5-11e4-9fda-ea13b6d5d4fb.png)

**Comment by dwlf** [comment]
This issue appears to be stale as there is no longer a browser window top right corner ribbon at http://nodejs.org/.

Can this be closed @Pana , @TooTallNate , @Volox , @gtramontina , @LegitTalon , @mtharrison ?

**Comment by mtharrison** [comment]
I think so

**Comment by robertkowalski** [comment]
was not able to reproduce on my own and closing given the feedback, thanks @mtharrison

**Comment by robertkowalski** [comment]
sorry, i just noticed it is still there: http://www.nodejs.org/industry/ :(

**Comment by fhemberger** [comment]
I just moved the directory `/industry/` from the server, as it hasn't been updated for a year. Closing this issue now.
