### ISSUE TITLE
Latest version is 0.10.32, but should be 0.10.33

### ISSUE THREAD

**Issue by misterdjules** [nodejs/nodejs.org-archive#54]
The latest version shown on the homepage as well as on the download page and the target of the install link is 0.10.32, but it should be 0.10.33.

**Comment by dshaw** [comment]
This has been fixed now, but there's no associated commit. Where is this managed and how can we prevent this from happening yet again? (This time around it was a security release too.)

**Comment by misterdjules** [comment]
@dshaw What "associated commit" are you referring to?

**Comment by Albert-IV** [comment]
If you look at the commit history, there doesn't seem to be a commit that changes the downloads page.  The last commit was from 5 days ago.

**Comment by misterdjules** [comment]
@droppedoncaprica Ok, thanks for the clarification!

**Comment by tjfontaine** [comment]
This was human error, in that I didn't type the right makefile command, I was meant to do the `release` rule, https://github.com/joyent/node-website/blob/master/Makefile#L77 instead I did the `blog` rule forgetting and therefore only updated the blog instead of both the website and the blog
