### ISSUE TITLE
Following folder links from `/docs/` dir doesn't work

### ISSUE THREAD

**Issue by chrisdickinson** [nodejs/nodejs.org-archive#56]
from joyent/node#4321:

> following folders links form http://nodejs.org/docs/, like to http://nodejs.org/docs/latest/ or  http://nodejs.org/docs/v0.8.15/
> 
> [actually] leads to http://nodejs.org/ homepage render
> 
> i presume there should be a redirect from /docs/:version/ to /docs/:version/api/

For instance, if you navigate [here](http://nodejs.org/docs/) and click on any version folder greater than 0.8 or so, you are redirected to the full site. This might not end up being a _huge_ issue, but it might be confusing for some.

**Comment by fitzage** [comment]
Hmm…it's not actually redirecting you to the homepage. It's showing the version of the homepage as it was when those old docs were current.

I'm not entirely sure why that is, but I believe this is actually an issue with the node repo and how the API docs are rendered, so your initial linked issue is probably the correct one. :-)

My guess is that the path was changed at some point, but the overview page that lists all the versions doesn't know that and links to them all the same. At any rate, this is actually handled by the node repo API docs generation at this point, and not by the website itself.

**Comment by robertkowalski** [comment]
seems quite similar to https://github.com/joyent/node-website/issues/69 - you have to add an /api to the url: http://nodejs.org/docs/v0.8.15/api/ works

**Comment by fhemberger** [comment]
Fixed on the new nodejs.org site.
