### ISSUE TITLE
Broken links in job page's header

### ISSUE THREAD

**Issue by misterdjules** [nodejs/nodejs.org-archive#57]
Both links to Node.js and Joyent in the job page's header are broken.

**Comment by kwhinnery** [comment]
Who owns this Simply Hired page? Probably a quick fix.

**Comment by chumbalayaa** [comment]
Looks like it's not even two links, it's just one big div (the entire top banner) with the same destination

**Comment by fhemberger** [comment]
I contacted Simply Hired on Twitter, maybe someone can help:
https://twitter.com/fhemberger/status/617305116119592960

**Comment by fhemberger** [comment]
Issue has been fixed by Simply Hired. Great support!
