### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by zachesposito** [nodejs/nodejs.org-archive#58]
Hello,

I noticed nodejs.org's current design is not responsive. Has there been any discussion around making it responsive? I would be willing to help if you think this would be useful.

Zach

**Comment by fhemberger** [comment]
@zesposi You're right, the current website is not responsive yet. I added PR #126 to make it at least readable on mobile devices.

I guess making the current website fully responsive/optimized for mobile doesn't have a high priority at the moment in light of the reconciliation with io.js. The upcoming merge of both projects will also bring a new technical foundation for the website, which will be also fully responsive.
