### ISSUE TITLE
redirect to https

### ISSUE THREAD

**Issue by robertkowalski** [nodejs/nodejs.org-archive#68]
All content on the node.js website should redirect to the https:// version - **except** everything at `/dist/`

**Comment by robertkowalski** [comment]
status update:
- doc.nodejs.org
- docs.nodejs.org
- api.nodejs.org

redirect now

**Comment by fhemberger** [comment]
`http://nodejs.org/foundation/blog.html` is not redirected to https.

**Comment by misterdjules** [comment]
@fhemberger Good catch, thank you :+1:

**Comment by fhemberger** [comment]
But I have no clue why it's the case. I can't see any rule in the nginx config that prevents redirection.
