### ISSUE TITLE
doc.nodejs.org redirect broken?

### ISSUE THREAD

**Issue by robertkowalski** [nodejs/nodejs.org-archive#69]
I am currently testing the https redirects, and I am not sure if I spotted a bug in the current nginx.conf:

http://doc.nodejs.org/v0.10.3 redirects me to https://nodejs.org/docs/v0.10.3/ but it should be https://nodejs.org/docs/v0.10.3/api/

code: https://github.com/joyent/node-website/blob/master/conf/nginx.conf#L126-130

**Comment by robertkowalski** [comment]
doc.nodejs.dev/v0.10.3/api works with the current redirect

**Comment by fhemberger** [comment]
Uhm, there is no 'api' in the redirect destination: https://github.com/nodejs/nodejs.org/blob/master/conf/nginx.conf#L108

**Comment by fhemberger** [comment]
Can't find a reference on Google for any site with links like http://doc.nodejs.org/v0.10.3
https://www.google.com/?q=link:doc.nodejs.org

Closing.
