### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by gtramontina** [nodejs/nodejs.org-archive#7]
Hi there,
I'm on a Chrome 33 and this is how the website looks like:
![screen shot 2014-03-10 at 10 49 22 am](https://f.cloud.github.com/assets/374635/2374116/d99e57c0-a85a-11e3-88f6-c0cda9abe47a.png)

Besides the already reported ugly ribbon #5, the "download" and "api" links are weird.

**Comment by fitzage** [comment]
It looks like you're not getting the correct font. Do you have typekit blocked?

I'll work on a better fallback font option for when Typekit isn't available.

**Comment by gtramontina** [comment]
True... I'm using [Ghostery](https://www.ghostery.com) and it is set to block typekit.
Feel free to close this issue, or keep it open 'till the fallback is in place.
Thanks!

**Comment by tjfontaine** [comment]
Should be fixed by #8
