### ISSUE TITLE
Enable TLS >1.0 | Disable SSL 3.0 | Enable ECDHE

### ISSUE THREAD

**Issue by ximex** [nodejs/nodejs.org-archive#75]
I tested the website with [sslyze](https://github.com/nabla-c0d3/sslyze/)

SCAN RESULTS FOR NODEJS.ORG:443 - 165.225.133.150:443

---
- Deflate Compression:
    OK - Compression disabled          
- Session Renegotiation:
    Client-initiated Renegotiations:   OK - Rejected
    Secure Renegotiation:              OK - Supported
- OpenSSL Heartbleed:
    OK - Not vulnerable to Heartbleed  
- Certificate - Content:
    SHA1 Fingerprint:                  9f554d8b1d118a77e98b209bf412b91a0a62846f
    Common Name:                       nodejs.org
    Issuer:                            thawte DV SSL CA - G2
    Serial Number:                     3B1458209F5222D2DEA6B16C2C48544C
    Not Before:                        Oct 17 00:00:00 2014 GMT
    Not After:                         Oct 17 23:59:59 2015 GMT
    Signature Algorithm:               sha256WithRSAEncryption
    Key Size:                          2048 bit
    Exponent:                          65537 (0x10001)
    X509v3 Subject Alternative Name:   {'DNS': ['nodejs.org']}
- Certificate - Trust:
    Hostname Validation:               OK - Subject Alternative Name matches
    "Mozilla NSS - 08/2014" CA Store:  OK - Certificate is trusted
    "Microsoft - 08/2014" CA Store:    OK - Certificate is trusted
    "Apple - OS X 10.9.4" CA Store:    OK - Certificate is trusted
    "Java 6 - Update 65" CA Store:     OK - Certificate is trusted
    Certificate Chain Received:        ['nodejs.org', 'thawte DV SSL CA - G2', 'thawte Primary Root CA']
- Certificate - OCSP Stapling:
    NOT SUPPORTED - Server did not send back an OCSP response.
- SSLV2 Cipher Suites:
    Server rejected all cipher suites.
- Session Resumption:
    With Session IDs:                  NOT SUPPORTED (0 successful, 5 failed, 0 errors, 5 total attempts).
    With TLS Session Tickets:          OK - Supported
- TLSV1_2 Cipher Suites:
    Server rejected all cipher suites.
- TLSV1_1 Cipher Suites:
    Server rejected all cipher suites.
- TLSV1 Cipher Suites:
    Preferred:  
               DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK  
    Accepted:  
               DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK  
               AES256-SHA                    -              256 bits      HTTP 200 OK  
               DHE-RSA-AES128-SHA            DH-1024 bits   128 bits      HTTP 200 OK  
               AES128-SHA                    -              128 bits      HTTP 200 OK  
               EDH-RSA-DES-CBC3-SHA          DH-1024 bits   112 bits      HTTP 200 OK  
               DES-CBC3-SHA                  -              112 bits      HTTP 200 OK                        
- SSLV3 Cipher Suites:
    Preferred:  
               DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK  
    Accepted:  
               DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK  
               AES256-SHA                    -              256 bits      HTTP 200 OK  
               DHE-RSA-AES128-SHA            DH-1024 bits   128 bits      HTTP 200 OK  
               AES128-SHA                    -              128 bits      HTTP 200 OK  
               EDH-RSA-DES-CBC3-SHA          DH-1024 bits   112 bits      HTTP 200 OK  
               DES-CBC3-SHA                  -              112 bits      HTTP 200 OK                        

Maybe this doc could help: https://bettercrypto.org/static/applied-crypto-hardening.pdf#subsection.2.1.3

**Comment by baslr** [comment]
+1

**Comment by baslr** [comment]
+1 plz upgrade to tls 1.2, cant connect anymore

**Comment by fhemberger** [comment]
Fixed.
