### ISSUE TITLE
Prevent users from deploying an outdated website unless they know what they're doing

### ISSUE THREAD

**Issue by misterdjules** [nodejs/nodejs.org-archive#78]
Recently, I uploaded an outdated version of the website by running `make release` in my local repository without having pulled the master branch beforehand.

Luckily, it was easily fixed by pulling the master branch and running `make website website-upload`, but the problem is sometimes not obvious to notice.

It seems it could be handy if the website deployment process would prompt the user whenever what's deployed is not the tip of joyent/node-website's master branch.

**Comment by misterdjules** [comment]
The fix for this issue is not necessarily to add a prompt to the current deployment process, it can also be to change the development process in a way that makes it impossible to deploy from something else than the tip of the master branch (or any other branch identified as the main branch).

**Comment by misterdjules** [comment]
@robertkowalski Awesome thanks!

**Comment by robertkowalski** [comment]
:)
