### ISSUE TITLE
remove duplicated templates, create navigation helper

### ISSUE THREAD

**Issue by robertkowalski** [nodejs/nodejs.org-archive#81]
We currently copy templates and slightly modify them in order to change the navigation items.

We already have some code for hightlighning in the footer: https://github.com/joyent/node-website/blob/master/doc/about/advisory-board/template.html#L102 we can add some other code for modifying the subpoints of the navigation.

Another solution would be to create a helper which would prebake all that in the basic markup automatically.

This affects currently the advisory board template in `about` and the core-team-page 

see also #80

**Comment by robertkowalski** [comment]
Just an idea - I am not a UX expert, but t least to me it is not obvious that there is more content like meetings behind some elements.

We could make them visible all the time:

![bildschirmfoto 2015-02-20 um 20 25 38](https://cloud.githubusercontent.com/assets/298166/6307749/c27bdfea-b93e-11e4-96c6-30b46b231feb.png)

@emilygit @fitzage what do you think?

**Comment by misterdjules** [comment]
Could you please elaborate on

> we can add some other code for modifying the subpoints of the navigation.

and on 

> Another solution would be to create a helper which would prebake all that in the basic markup automatically.

?
I'm not sure I understand what you mean.

Thanks!

**Comment by robertkowalski** [comment]
> we can add some other code for modifying the subpoints of the navigation.

In https://github.com/joyent/node-website/blob/master/doc/about/advisory-board/template.html#L102 we already have something like a client-side navigation in JavaScript. It currently just adds different classes to the markup so the point in the navigation gets a green background. We could add some more lines of JS to it, that the navigation automatically adds/remove sub-points based on the chosen main-section. That should be quite easy.

> Another solution would be to create a helper which would prebake all that in the basic markup automatically.

The website is built statically from markdown and html templates. It reminds a bit me of jekyll and related systems. We could render different navigations when running make und put it in a placeholder, e.g. `__navigation__` - the helper takes values from the `index.json` and adds the subnavigation-points and also the `active`-class. The nice thing about this approach is that we can throw the jquery based frontend code away instead of adding more of it. Example `index.json`:

``` js
{ 
  "template": "doc/about/core-team/template.html", 
  "title": "Core Team", 
  "subnav": [{"title": "Meeting Minutes", "href": "/about/meeting-minutes"}] 
}
```

When the processor processes `about.md` it will insert a generated html in it for the navigation. As we should know which site we are processing (about.html) we can set the the class to active in the generated markup for it. It also knows that the navigation on this page should get additional points from the index.json (`subnav` property). So every page get's a slightly customized generated navigation.

cons: more overhead with json properties
pro: we get rid of the inline script on every page (which currently just highlights navigation points)

**Comment by misterdjules** [comment]
@robertkowalski Thanks for the clarification!

Intuitively I like the second solution (adding some metadata in index.json files) better, but I'd like to get some feedback from @fitzage and @tjfontaine too.
