### ISSUE TITLE
Add nodejsguru.com to the list of tutorials

### ISSUE THREAD

**Issue by nodejsguru** [nodejs/nodejs.org-archive#87]
Hi,

This is a request to add [nodeJSguru](nodejsguru.com) under the Learning section of Community page. There is a link to [How To Node](http://howtonode.org/) but this is not being maintained actively anymore. At nodeJSguru we intend to work on the learning side of node.js as well as build a community of practitioners with job boards and discussion forums. A link on nodejs.org would help us immensely.

Thanks.

**Comment by robertkowalski** [comment]
Hi and thank you for your contribution!

I'm not sure about this as How to Node is a community project while it seems that nodeJSguru is a paid service that is not possible to use without paying $300 for it (even after sign up).

I am -1 adding the site as a listing for tutorials at https://nodejs.org/community/#index_md_learning

If no one else objects I would close this issue in 48hrs

**Comment by nodejsguru** [comment]
Hi, I understand. Yes, we are a paid service and from what you suggest this space is limited to free stuff.  No problem, you may close the issue.
