### ISSUE TITLE
Mailing List Feature to Subscribe to Your Blog

### ISSUE THREAD

**Issue by zhanzhenzhen** [nodejs/nodejs.org-archive#97]
I think many people would like the website to add a mailing list feature (not on Google Groups) in order to be notified of big events like software updates (especially those containing openssl updates). I really fear that there will be another "heartbleed". I now just check your website everyday, which is very inefficient.

**Comment by robertkowalski** [comment]
Hi @zhanzhenzhen,

do you know the https://groups.google.com/forum/#!forum/nodejs-sec list which is made exactly for those updates?

What do you mean by add a mailing list feature (not on Google Groups) - why is Google Groups not working for you?

**Comment by zhanzhenzhen** [comment]
I don't know the "nodejs-sec" list. It seems very rarely updated. The most recent 0.12.1 which contains OpenSSL bug fixes wasn't posted there. I want a mailing list that sends all official announcements and nothing else. Google Group's mailing list doesn't have an option to only receive posts from a specific user.

**Comment by robertkowalski** [comment]
would our rss feed of the official blog help you for that use case? most
email clients support rss: http://blog.nodejs.org/feed/

On Fri, Mar 27, 2015 at 3:27 PM, Zhenzhen Zhan 詹臻臻 <notifications@github.com

**Comment by zhanzhenzhen** [comment]
Yes this seems to be the only way. But Apple Mail deleted RSS support. But yesterday I found a free RSS email delivery service, then tested and found it work very well. I used this address "http://feeds.feedburner.com/nodejs/123123123", but yours is better, I will change to yours.

**Comment by robertkowalski** [comment]
Cool! Glad we found a solution :)
